import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Car-Rental App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html data-theme="light">
        <body className={inter.className}>
          <SignedIn>
            {" "}
            <Navbar />
            {children}
          </SignedIn>
          <SignedOut>
            <SignedIn />
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
